
const SHOPIFY_COLLECTION="https://lalittletribu.fr/collections/nouveautes/products.json?limit=250";
const LOGO_URL="https://lalittletribu.fr/cdn/shop/files/LLT_logo_VF_2a1e1503-fb7b-49b7-9c92-44832dae32e8.png?v=1732204972&width=350";
const state={products:[],source:"loading",selection:JSON.parse(localStorage.getItem("llt_selection_v08")||"[]"),category:"Tous",signature:null};
const qs=new URLSearchParams(location.search);
const campaign={source:qs.get("utm_source")||qs.get("src")||"direct",medium:qs.get("utm_medium")||"web",campaign:qs.get("utm_campaign")||"wholesale_demo"};
function money(v){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(Number(v||0))}
function track(type,payload={}){const k="llt_events_v08",e=JSON.parse(localStorage.getItem(k)||"[]");e.push({type,at:new Date().toISOString(),...campaign,...payload});localStorage.setItem(k,JSON.stringify(e))}
function category(t){t=t.toLowerCase();if(t.includes("bracelet"))return"Bracelets";if(t.includes("collier")||t.includes("croix"))return"Colliers";if(t.includes("pochette"))return"Accessoires";if(t.includes("médaille")||t.includes("medaille"))return"Pendentifs";return"Nouveautés"}
function normalize(p){const prices=(p.variants||[]).map(v=>Number(v.price||0)).filter(n=>!Number.isNaN(n));const min=prices.length?Math.min(...prices):0,max=prices.length?Math.max(...prices):min;return{id:String(p.id),name:p.title,price:(min!==max?"Dès ":"")+money(min),category:category(p.title),source:`https://lalittletribu.fr/products/${p.handle}`,variants:(p.variants||[]).map(v=>v.title).filter(v=>v&&v!=="Default Title"),note:"Nouveauté Lalittletribu",image:p.images?.[0]?.src||p.image?.src||null}}
async function load(){try{const r=await fetch(SHOPIFY_COLLECTION,{mode:"cors",cache:"no-store"});if(!r.ok)throw 0;const d=await r.json();state.products=(d.products||[]).map(normalize);state.source="shopify-live"}catch(e){state.products=await fetch("products.json?v=082").then(r=>r.json());state.source="fallback"}}
function product(id){return state.products.find(p=>String(p.id)===String(id))}
function quickView(id){const p=product(id),opts=(p.variants?.length?p.variants:["Standard"]).map(v=>`<option>${v}</option>`).join("");document.body.insertAdjacentHTML("beforeend",`<div class="modal" onclick="if(event.target===this)this.remove()"><div class="modal-card"><button class="modal-close" type="button" aria-label="Fermer" onclick="this.closest('.modal').remove()">×</button><div class="qv"><div class="qv-media">${p.image?`<img src="${p.image}" alt="">`:""}</div><div class="qv-info"><div class="eyebrow">${p.category}</div><h2>${p.name}</h2><div><span class="price-label">Prix public conseillé</span><strong>${p.price}</strong></div><div class="qv-note">${p.note||""}</div><label class="field">Variante<select name="variant">${opts}</select></label><label class="field">Quantité<input name="qty" type="number" min="1" value="1"></label><button class="btn" onclick="addFromModal('${p.id}',this)">Ajouter à ma sélection</button><button class="pill" onclick="this.closest('.modal').remove()">Continuer mes choix</button></div></div></div></div>`);track("quick_view",{product:id})}
function addFromModal(id,btn){const m=btn.closest(".modal"),p=product(id),v=m.querySelector("[name=variant]").value,q=Number(m.querySelector("[name=qty]").value||1);add(p,v,q);m.remove()}
function quickAdd(id){const p=product(id),v=(p.variants&&p.variants[0])||"Standard";add(p,v,1)}
function add(p,v,q){const x=state.selection.find(s=>String(s.id)===String(p.id)&&s.variant===v);if(x)x.qty+=q;else state.selection.push({id:p.id,name:p.name,variant:v,qty:q,price:p.price,image:p.image||""});save();track("add_to_selection",{product:p.id,variant:v,qty:q});render()}
function save(){localStorage.setItem("llt_selection_v08",JSON.stringify(state.selection))}
function changeQty(i,d){state.selection[i].qty=Math.max(1,state.selection[i].qty+d);save();document.querySelector(".drawer")?.remove();render();openSelection()}
function removeItem(i){state.selection.splice(i,1);save();document.querySelector(".drawer")?.remove();render();openSelection()}
function openSelection(){document.body.insertAdjacentHTML("beforeend",drawer())}
function drawer(){const total=state.selection.reduce((a,b)=>a+b.qty,0),rows=state.selection.map((x,i)=>`<div class="sel-row">${x.image?`<img src="${x.image}" alt="">`:"<div></div>"}<div><div class="sel-name">${x.name}</div><div class="tiny">${x.variant}</div><div class="sel-tools"><div class="stepper"><button onclick="changeQty(${i},-1)">−</button><span>${x.qty}</span><button onclick="changeQty(${i},1)">+</button></div><button class="remove" onclick="removeItem(${i})">Retirer</button></div></div></div>`).join("");return `<aside class="drawer"><div class="drawer-head"><div><div class="eyebrow">Votre sélection</div><h2>${total} pièce${total>1?"s":""}</h2></div><button class="pill" onclick="this.closest('.drawer').remove()">Fermer</button></div>${rows||"<p>Votre sélection est encore vide.</p>"}${state.selection.length?`<div class="final-box"><button class="btn" onclick="showFinalForm()">Présenter ma sélection à Lalittletribu</button><p class="tiny">Aucune commande n'est passée à ce stade.</p></div>`:""}</aside>`}
function showFinalForm(){document.querySelector(".drawer")?.remove();document.body.insertAdjacentHTML("beforeend",`<div class="modal" onclick="if(event.target===this)this.remove()"><div class="modal-card"><button class="modal-close" type="button" aria-label="Fermer" onclick="this.closest('.modal').remove()">×</button><div class="eyebrow">Dernière étape</div><h2>Parlons de votre projet.</h2><p>Votre sélection est prête. Dites-nous simplement ce que vous imaginez avec Lalittletribu.</p><form onsubmit="event.preventDefault();finish(this)"><label class="field">Votre projet<select name="project" required><option value="">Choisir…</option><option>Je souhaite distribuer Lalittletribu</option><option>Je souhaite organiser un atelier / événement</option><option>J’ai une idée de collaboration</option><option>Autre</option></select></label><div class="grid2"><label class="field">Prénom<input name="firstname" required></label><label class="field">Nom<input name="lastname" required></label><label class="field">Boutique / enseigne<input name="shop" required></label><label class="field">E-mail professionnel<input name="email" type="email" required></label><label class="field">Téléphone<input name="phone" type="tel"></label><label class="field">Ville<input name="city" required></label></div><label class="tiny" style="display:block;margin:14px 0"><input type="checkbox" required> J’accepte que ces informations soient utilisées pour le suivi de ma demande professionnelle.</label><button class="btn" style="width:100%">Présenter ma sélection à Lalittletribu</button></form><p class="tiny">Version de démonstration : aucune commande ni paiement n'est effectué.</p></div></div>`)}
function finish(form){const lead={...Object.fromEntries(new FormData(form).entries()),...campaign,created_at:new Date().toISOString(),selection:state.selection};localStorage.setItem("llt_demo_request_v08",JSON.stringify(lead));track("selection_finalized",{shop:lead.shop,items:state.selection.length,units:state.selection.reduce((a,b)=>a+b.qty,0)});document.querySelector(".modal")?.remove();document.body.insertAdjacentHTML("beforeend",`<div class="modal"><div class="modal-card confirm"><div class="heart">♥</div><div class="eyebrow">Lalittletribu</div><h2>Votre sélection est prête.</h2><p>Merci ${lead.firstname}. Lalittletribu pourra revenir vers <strong>${lead.shop}</strong> pour finaliser votre demande revendeur.</p><div class="summary"><strong>${state.selection.reduce((a,b)=>a+b.qty,0)} pièce(s)</strong> · ${state.selection.length} référence(s)<br><span class="tiny">Cette version est une démonstration : la transmission réelle sera connectée après validation du dispositif.</span></div><button class="btn" onclick="this.closest('.modal').remove()">Revenir au showroom</button></div></div>`)}
function card(p){return `<article class="product" onclick="quickView('${p.id}')"><div class="visual ${p.image?"":"placeholder"}">${p.image?`<img src="${p.image}" alt="${p.name.replaceAll('"','&quot;')}" loading="lazy">`:p.name.slice(0,2).toUpperCase()}<div class="badge">NOUVEAUTÉ</div></div><div class="card-info"><div class="meta">${p.category}<span class="price-label">Prix public conseillé</span>${p.price}</div><h3>${p.name}</h3><div class="card-actions"><button class="btn" onclick="event.stopPropagation();quickAdd('${p.id}')">+ Sélection</button></div></div></article>`}
function signatureProducts(label){const l=label.toLowerCase();return state.products.filter(p=>{const n=p.name.toLowerCase();if(l==="iconique")return n.includes("iconique");if(l.includes("maxi"))return n.includes("maxi")&&n.includes("cœur")||n.includes("maxi")&&n.includes("coeur");if(l.includes("médailles"))return n.includes("médaille")||n.includes("medaille")||n.includes("pierre");if(l==="croix")return n.includes("croix");if(l==="grigris")return n.includes("grigri");return false})}
function showSignature(label){state.signature=label;state.category="Tous";render();document.querySelector('#showroom').scrollIntoView({behavior:'smooth'})}
function signatureCard(label){const p=signatureProducts(label).find(x=>x.image)||signatureProducts(label)[0];return `<button class="signature-card" onclick="showSignature('${label.replaceAll("'","\'")}')" aria-label="Voir ${label} dans la collection">${p?.image?`<img src="${p.image}" alt="" loading="lazy">`:``}<span>${label}</span></button>`}
function render(){
 const cats=["Tous",...new Set(state.products.map(p=>p.category))],shown=state.signature?signatureProducts(state.signature):(state.category==="Tous"?state.products:state.products.filter(p=>p.category===state.category)),count=state.selection.reduce((a,b)=>a+b.qty,0);
 document.querySelector("#app").innerHTML=`
 <header class="top top-hidden" id="siteHeader"><div class="wrap nav"><div class="brand"><img class="logo-img" src="${LOGO_URL}" alt="La Little Tribu"><span class="wholesale">ESPACE PRO</span></div><nav class="desktop-nav"><a href="#univers">L'univers</a><a href="#signatures">Les signatures</a><a href="#showroom">Nouveautés</a><a href="#personnalisation">Personnalisation</a></nav><div class="nav-actions"><button class="retailer-link" disabled title="Disponible dans une prochaine version">Déjà revendeur ?</button><button class="pill selection-nav" onclick="openSelection()">Ma sélection (${count})</button></div></div></header>
 <main>
  <section class="barbara-cover" id="cover"><img src="hero-barbara.jpeg" alt="La Little Tribu — Happy family concept store — Collection & offre professionnelle"><a class="cover-hotspot" href="#univers"><span>COLLECTION &amp; OFFRE PROFESSIONNELLE</span></a></section>

  <section id="univers" class="lookbook-section universe"><div class="wrap lookbook-grid"><div class="lookbook-copy"><div class="eyebrow">Notre univers</div><h1>Des bijoux joyeux,<br>personnels et porte-bonheur</h1><p>La Little Tribu imagine à Boulogne-Billancourt des bijoux colorés et personnalisables, pensés comme de petits cadeaux qui racontent une histoire.</p><p>Des pièces faciles à offrir, à collectionner et à assortir : bracelets Cœur, médailles miraculeuses, croix en pierres naturelles et grigris.</p><div class="adn"><span>ADN DE MARQUE</span><strong>Couleur • personnalisation • famille<br>Porte-bonheur • petites séries</strong></div></div><figure class="lookbook-image"><img src="lookbook-univers.jpeg" alt="Bijou La Little Tribu"></figure></div></section>

  <section id="signatures" class="lookbook-section signatures-v09"><div class="wrap"><div class="eyebrow">Nos signatures</div><h2>Les Cœurs</h2><div class="signature-feature"><figure><img src="lookbook-coeurs.jpeg" alt="Bracelets Cœur La Little Tribu"></figure><div class="signature-text"><article><span class="label-chip">L’ICONIQUE</span><p>Bracelet Cœur coloré, avec ou sans lien textile. Décliné pour les adultes, les enfants et les duos.</p></article><article><span class="label-chip">LE MAXI CŒUR</span><p>Une version plus affirmée : coloris Léo ou palette vitaminée, cœur central contrasté et médaille en option.</p></article><div class="pro-note"><strong>Bracelet Cœur iconique</strong><span>Prix public conseillé : 20 € TTC</span><small>Les tarifs et conditions professionnels seront intégrés dans la prochaine version.</small></div></div></div></div></section>

  <section class="lookbook-section stones"><div class="wrap"><div class="eyebrow">Nouvelle collection</div><h2>Médailles &amp; pierres</h2><div class="stone-grid"><div><h3>PORTE-BONHEUR À COMPOSER</h3><p>Médailles miraculeuses, croix en pierres naturelles, scarabées et médaillons colorés. Montage sur cordon, chaîne fine dorée ou chaîne à boules.</p><div class="shop-offer"><span>OFFRE BOUTIQUE</span><p>Sélection prête à vendre ou assortiment construit ensemble. Couleurs, finitions et quantités adaptées à votre univers.</p></div></div><figure><img src="lookbook-medaille.jpeg" alt="Médaille La Little Tribu"></figure></div></div></section>

  <section id="showroom" class="wrap section showroom-section"><div class="section-head"><div><div class="eyebrow">Collection &amp; offre professionnelle</div><h2>Les nouveautés</h2><p class="section-sub">Composez votre première sélection à partir des nouveautés La Little Tribu. Choisissez vos références, variantes et quantités avant de vous identifier.</p><div class="status">${state.signature?`Sélection : ${state.signature} · ${shown.length} référence${shown.length>1?"s":""}`:`${state.products.length} références · ${state.source==="shopify-live"?"collection Shopify à jour":"catalogue de secours"}`}</div></div><div class="filters">${cats.map(c=>`<button class="pill ${c===state.category?"active":""}" onclick="state.signature=null;state.category='${c}';render();document.querySelector('#showroom').scrollIntoView()">${c}</button>`).join("")}</div></div><div class="products">${shown.map(card).join("")}</div></section>

  <section id="personnalisation" class="lookbook-section personalization"><div class="wrap personalization-grid"><div><div class="eyebrow light">Animations</div><h2>La personnalisation<br>en boutique</h2><p class="personal-lead">Un bar créatif qui attire, fait rester et transforme le passage en expérience.</p><div class="personal-list"><article><span>BAR À BIJOUX</span><p>Bracelets, colliers, médailles et grigris composés sur place.</p><button onclick="interest('Bar à bijoux')">Je suis intéressé(e) →</button></article><article><span>ÉVÉNEMENTS PRIVÉS</span><p>Anniversaires, EVJF, bar-mitsvah et événements d’entreprise.</p><button onclick="interest('Événements privés')">Je suis intéressé(e) →</button></article><article><span>FORMAT SUR MESURE</span><p>Atelier défini selon le public, la durée et l’espace disponible.</p><button onclick="interest('Format sur mesure')">Je suis intéressé(e) →</button></article></div><div class="references">Références : <strong>Maison Paulette</strong> • ateliers enfants • événements privés • personnalisation en point de vente</div></div><figure><img src="lookbook-coeurs.jpeg" alt="La Little Tribu en boutique"></figure></div></section>

  <section id="collaborer" class="lookbook-section work"><div class="wrap"><div class="eyebrow">Travaillons ensemble</div><h2>Une offre simple et souple</h2><div class="work-list"><article><span>COMMANDE PROFESSIONNELLE</span><p>Sélection de pièces, assortiment de couleurs et production en petites séries.</p><a href="#showroom">Composer ma sélection →</a></article><article><span>PERSONNALISATION</span><p>Prénoms, messages, choix des liens, pierres, médailles et finitions.</p><button onclick="interest('Personnalisation')">Parler de mon projet →</button></article><article><span>RÉASSORT</span><p>Suivi direct, réassort selon les disponibilités et nouveautés régulières.</p></article><article><span>ANIMATION BOUTIQUE</span><p>Journée ou demi-journée de personnalisation pour créer du trafic et du contenu.</p><button onclick="interest('Animation boutique')">Parler de mon projet →</button></article></div><div class="contact-book"><span>CONTACT</span><p>Instagram : @lalittletribu<br>Boutique : lalittletribu.fr<br>Commandes et ateliers : par message ou e-mail</p></div></div></section>

  <footer class="pro-footer"><div class="wrap footer-grid"><div><img class="footer-logo" src="${LOGO_URL}" alt="La Little Tribu"><p>Collection &amp; offre professionnelle</p></div><div class="social-links"><a href="https://www.instagram.com/lalittletribu/" target="_blank" rel="noopener" aria-label="Instagram La Little Tribu"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1"/></svg><span>Instagram</span></a><a href="https://lalittletribu.fr/" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3 4 6 4 9s-1 6-4 9c-3-3-4-6-4-9s1-6 4-9z"/></svg><span>lalittletribu.fr</span></a><a href="mailto:barbara@lalittletribu.fr"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/></svg><span>Contact</span></a></div></div></footer>
 </main>${count?`<div class="selectbar"><span><strong>${count}</strong> pièce${count>1?"s":""} dans votre sélection</span><button class="btn" onclick="openSelection()">Voir / finaliser</button></div>`:""}`;
 setupHeader();
}
function setupHeader(){const h=document.querySelector('#siteHeader'),c=document.querySelector('#cover');if(!h||!c)return;const o=new IntersectionObserver(([e])=>h.classList.toggle('top-hidden',e.isIntersecting&&e.intersectionRatio>.12),{threshold:[0,.12]});o.observe(c)}
function interest(kind){document.body.insertAdjacentHTML("beforeend",`<div class="modal" onclick="if(event.target===this)this.remove()"><div class="modal-card"><button class="modal-close" type="button" aria-label="Fermer" onclick="this.closest('.modal').remove()">×</button><div class="eyebrow">Votre projet</div><h2>${kind}</h2><p>Cette intention sera reprise dans votre demande professionnelle.</p><form onsubmit="event.preventDefault();this.closest('.modal').remove();showFinalFormWithProject('${kind.replaceAll("'","\\'")}')"><button class="btn" style="width:100%">Continuer</button></form><button class="pill" style="width:100%;margin-top:8px" onclick="this.closest('.modal').remove()">Retour</button></div></div>`)}
function showFinalFormWithProject(kind){showFinalForm();const s=document.querySelector('.modal select[name=project]');if(s){const match=[...s.options].find(o=>o.textContent.includes('atelier')||o.textContent.includes('collaboration'));if(kind.toLowerCase().includes('bar')||kind.toLowerCase().includes('événement')||kind.toLowerCase().includes('animation')||kind.toLowerCase().includes('format'))s.value='Je souhaite organiser un atelier / événement';else if(kind.toLowerCase().includes('personnal'))s.value='J’ai une idée de collaboration'}}
(async()=>{await load();track("page_view",{catalog_source:state.source});render()})();

document.addEventListener("keydown",e=>{
  if(e.key==="Escape"){
    document.querySelector(".modal")?.remove();
    document.querySelector(".drawer")?.remove();
  }
});
