
const SHOPIFY_COLLECTION="https://lalittletribu.fr/collections/nouveautes/products.json?limit=250";
const state={products:[],source:"loading",lead:JSON.parse(localStorage.getItem("llt_lead_v03")||"null"),selection:JSON.parse(localStorage.getItem("llt_selection_v03")||"[]"),category:"Tous"};
const qs=new URLSearchParams(location.search);
const campaign={source:qs.get("utm_source")||qs.get("src")||"direct",medium:qs.get("utm_medium")||"web",campaign:qs.get("utm_campaign")||"wholesale_preview"};
function money(cents){return new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(Number(cents)/100)}
function track(type,payload={}){const k="llt_events_v03";const e=JSON.parse(localStorage.getItem(k)||"[]");e.push({type,at:new Date().toISOString(),...campaign,...payload});localStorage.setItem(k,JSON.stringify(e))}
function guessCategory(title){title=title.toLowerCase();if(title.includes("bracelet"))return"Bracelets";if(title.includes("collier")||title.includes("croix"))return"Colliers";if(title.includes("pochette"))return"Accessoires";if(title.includes("médaille")||title.includes("medaille"))return"Pendentifs";return"Nouveautés"}
function normalizeShopify(p){
 const prices=(p.variants||[]).map(v=>Number(v.price||0)).filter(Boolean);const min=prices.length?Math.min(...prices):0;const max=prices.length?Math.max(...prices):min;
 return {id:String(p.id),name:p.title,price:(min!==max?"Dès ":"")+money(min*100),category:guessCategory(p.title),source:`https://lalittletribu.fr/products/${p.handle}`,variants:(p.variants||[]).map(v=>v.title).filter(v=>v&&v!=="Default Title"),note:"Nouveauté La Little Tribu",image:p.images?.[0]?.src||p.image?.src||null,images:(p.images||[]).map(i=>i.src)};
}
async function loadProducts(){
 try{
  const r=await fetch(SHOPIFY_COLLECTION,{mode:"cors",cache:"no-store"});
  if(!r.ok)throw new Error("HTTP "+r.status);
  const data=await r.json(); state.products=(data.products||[]).map(normalizeShopify);state.source="shopify-live";
 }catch(e){
  state.products=await fetch("products.json").then(r=>r.json());state.source="fallback";
 }
}
function ensureLead(){if(state.lead)return true;document.body.insertAdjacentHTML("beforeend",leadModal());return false}
function saveLead(form){const d=Object.fromEntries(new FormData(form).entries());state.lead={...d,...campaign,created_at:new Date().toISOString()};localStorage.setItem("llt_lead_v03",JSON.stringify(state.lead));track("lead_created",{shop:d.shop,city:d.city});document.querySelector(".modal")?.remove();render()}
function addItem(id){if(!ensureLead())return;const p=state.products.find(x=>String(x.id)===String(id));const v=document.querySelector(`[data-variant="${CSS.escape(String(id))}"]`)?.value||"Standard";const q=Number(document.querySelector(`[data-qty="${CSS.escape(String(id))}"]`)?.value||1);const ex=state.selection.find(x=>String(x.id)===String(id)&&x.variant===v);if(ex)ex.qty+=q;else state.selection.push({id,name:p.name,variant:v,qty:q,price:p.price});localStorage.setItem("llt_selection_v03",JSON.stringify(state.selection));track("add_to_selection",{product:id,variant:v,qty:q});render()}
function removeItem(i){state.selection.splice(i,1);localStorage.setItem("llt_selection_v03",JSON.stringify(state.selection));document.querySelector(".drawer")?.remove();render();openSelection()}
function openSelection(){document.body.insertAdjacentHTML("beforeend",drawer())}
function leadModal(){return `<div class="modal"><div class="modal-card"><div class="eyebrow">Accès professionnel</div><h2>Composez votre sélection.</h2><p>Identifiez votre boutique pour sauvegarder vos choix et permettre à La Little Tribu de reprendre contact avec vous.</p><form onsubmit="event.preventDefault();saveLead(this)"><div class="grid2"><label class="field">Prénom<input name="firstname" required></label><label class="field">Nom<input name="lastname" required></label><label class="field">Boutique / enseigne<input name="shop" required></label><label class="field">E-mail professionnel<input name="email" type="email" required></label><label class="field">Téléphone<input name="phone" type="tel"></label><label class="field">Ville<input name="city" required></label><label class="field">Code postal<input name="postal" required></label><label class="field">Type de point de vente<select name="type"><option>Concept store</option><option>Boutique bijoux / accessoires</option><option>Boutique mode</option><option>Grand magasin</option><option>Autre</option></select></label></div><label class="tiny" style="display:block;margin:15px 0"><input type="checkbox" required> J’accepte que ces informations soient utilisées pour répondre à ma demande professionnelle et assurer le suivi commercial.</label><button class="btn" style="width:100%">Continuer</button></form><p class="tiny">Prototype : la collecte centralisée sera branchée après validation du parcours.</p></div></div>`}
function card(p){
 const opts=(p.variants?.length?p.variants:["Standard"]).map(v=>`<option>${v}</option>`).join("");
 const media=p.image?`<div class="visual"><img src="${p.image}" alt="${p.name.replaceAll('"','&quot;')}" loading="lazy"><div class="badge">NOUVEAUTÉ</div></div>`:`<div class="visual placeholder">${p.name.slice(0,2).toUpperCase()}<div class="badge">NOUVEAUTÉ</div></div>`;
 return `<article class="product">${media}<div class="info"><div class="meta"><span>${p.category}</span><span>${p.price}</span></div><h3>${p.name}</h3><div class="note">${p.note||""}</div><a class="link" href="${p.source}" target="_blank" rel="noopener">Voir la fiche LLT ↗</a><div class="controls"><select data-variant="${p.id}">${opts}</select><input data-qty="${p.id}" type="number" min="1" value="1"><div class="locked">Tarifs et conditions revendeur après validation.</div><button class="btn" style="width:100%;margin-top:10px" onclick="addItem('${p.id}')">${state.lead?"Ajouter à ma sélection":"Composer ma sélection"}</button></div></div></article>`;
}
function drawer(){const rows=state.selection.map((x,i)=>`<div class="row"><strong>${x.name}</strong><div class="tiny">${x.variant} · quantité ${x.qty}</div><button class="pill" onclick="removeItem(${i})">Retirer</button></div>`).join("");return `<aside class="drawer"><div class="drawer-head"><div><div class="eyebrow">Revendeur</div><h2>Ma sélection</h2></div><button class="pill" onclick="this.closest('.drawer').remove()">Fermer</button></div>${state.lead?`<p class="tiny">${state.lead.shop} · ${state.lead.city}</p>`:""}${rows||"<p>Aucune pièce sélectionnée.</p>"}</aside>`}
function render(){
 const cats=["Tous",...new Set(state.products.map(x=>x.category))];const shown=state.category==="Tous"?state.products:state.products.filter(x=>x.category===state.category);const count=state.selection.reduce((a,b)=>a+b.qty,0);const hero=state.products.find(p=>p.image)?.image;
 document.querySelector("#app").innerHTML=`<header class="top"><div class="wrap nav"><div class="logo">La Little Tribu <small>WHOLESALE</small></div><div><span class="status hide-mobile">${state.source==="shopify-live"?"Catalogue LLT live":"Catalogue local"}</span> <button class="pill" onclick="openSelection()">Ma sélection (${count})</button></div></div></header><main><section class="wrap hero"><div><div class="eyebrow">Showroom professionnel · Nouveautés</div><h1>La Little Tribu, à découvrir en boutique.</h1><p class="lead">Les dernières créations de La Little Tribu dans un showroom pensé pour les boutiques et concept stores. Découvrez la collection puis composez votre sélection.</p><div class="cta"><a class="btn" href="#showroom">Découvrir les nouveautés</a><a class="btn secondary" href="https://lalittletribu.fr" target="_blank">Voir la boutique</a></div></div><div class="hero-photo ${hero?"":"fallback"}">${hero?`<img src="${hero}" alt="La Little Tribu">`:""}</div></section><section id="showroom" class="wrap section"><div class="section-head"><div><div class="eyebrow">Collection pilote</div><h2>Nouveautés</h2><p class="lead" style="font-size:16px">${state.products.length} références chargées · ${state.source==="shopify-live"?"données Shopify en direct":"fallback local"}</p></div><div class="filters">${cats.map(c=>`<button class="pill ${c===state.category?"active":""}" onclick="state.category='${c}';render();document.querySelector('#showroom').scrollIntoView()">${c}</button>`).join("")}</div></div><div class="products">${shown.map(card).join("")}</div></section></main>${count?`<div class="selectbar"><span><strong>${count} pièce(s)</strong> sélectionnée(s)</span><button class="btn" onclick="openSelection()">Voir ma sélection</button></div>`:""}`;
}
(async()=>{await loadProducts();track("page_view",{catalog_source:state.source});render()})();
